name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux(Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 11

      - name: Build JNI Native Library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build Mirai Plugin
        run: |
          chmod +x gradlew
          ./gradlew build

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 11

      - name: JNI Native Library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build Mirai Plugin
        run: |
          chmod +x gradlew
          ./gradlew build

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 11

      - name: JNI Native Library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build Mirai Plugin
        run: |
          chmod +x gradlew
          ./gradlew build
