name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux(Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build jni native library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build mirai plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build jni native library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build mirai plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build jni native library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build mirai plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin
