name: Build

on:
  release:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux(Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 11

      - name: Build jni native library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build mirai plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin
          ./gradlew buildPluginLegacy

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/build/mirai/*

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 11

      - name: Build jni native library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build mirai plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin
          ./gradlew buildPluginLegacy

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/build/mirai/*

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 11

      - name: Build jni native library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build mirai plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin
          ./gradlew buildPluginLegacy

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/build/mirai/*
