name: Release Artifact

on:
  release:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: microsoft
          java-version: 17

      - name: Build JNI Native Library
        run: |
          chmod +x gradlew
          ./gradlew buildJniNative

      - name: Build Boot Jar
        id: build_plugin
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          ./gradlew version
          echo "::set-output name=artifact_name::$(cat version)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build_plugin.outputs.artifact_name }}
          path: ${{ github.workspace }}/build/libs/${{ steps.build_plugin.outputs.artifact_name }}
